sudo: false
language: ruby
rvm:
  - 2.1.6
  - 2.2.4
env:
  - RAILS_VERSION=4.0.13
  - RAILS_VERSION=4.1.15
  - RAILS_VERSION=4.2.7
before_script: gem install bundler -v 1.12.5
script: bundle exec rspec
